server:
  port: 6002
  
spring:
  application:
    name: appgateway
  cloud:
   gateway:
    discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
        default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
    routes:      
      
      - id: MsProducto
        uri: http://localhost:85
        predicates:
            - Path=/api/**

    
 

 